spring.application.name=Precious Time

spring.jpa.open-in-view=false

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=create-drop

jwt.secret=qwepiruqewpoirqewurpioqueproquwerpoqiewruqieworupqwioerqipweourqwepioruqewruipo
jwt.duration=86400