spring.application.name=Precious Time

spring.jpa.open-in-view=false

spring.jpa.show-sql=true

spring.datasource.url=jdbc:h2:./db/basedatos
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop

jwt.secret=
jwt.duration=86400